# Based on https://github.com/moteus/lua-travis-example
language: c
branches:
  only:
    - moon
env:
  global:
    - LUAROCKS=2.3.0
    - LUA=lua5.1
before_install:
  - source .travis/setenv_lua.sh
install:
  - luarocks install moonscript
script:
  - cd build
  - rm -r *
  - moonc -l ../src
  - moonc -t . ../src/*
notifications:
  irc:
    channels:
      - "irc.esper.net#cc.ru"
    use_notice: true
    template:
      - "\x0300,01New build on \x02%{repository_slug}\x02!"
      - "\x02%{repository_name}#%{build_number}\x02 [\x1f%{branch}\x1f] %{message}"
      - "[\x1f%{commit}\x1f] \x02%{author}\x02: %{commit_message}"
      - "\x02Changes:\x02 %{compare_url}"
      - "\x02Build details:\x02 %{build_url}"
