language: c
env:
  global:
  - LUAROCKS=2.3.0
  - LUA=lua5.1
  - BUILD='release'
addons:
  apt:
    packages:
    - python3
    - curl
before_install:
- openssl aes-256-cbc -K $encrypted_fd3ec3406f90_key -iv $encrypted_fd3ec3406f90_iv -in publish.sh.enc -out .travis/publish.sh -d
- source .travis/setenv_lua.sh
install:
- luarocks install moonscript
- source .travis/install-luaminify.sh
script:
- bash ./build.sh
after_success:
- bash .travis/publish.sh
notifications:
  irc:
    channels:
    - irc.esper.net#cc.ru
    use_notice: true
    template:
    - "\x02%{repository_name}#%{build_number}\x02 [\x1F%{branch}\x1F] \x1F%{message}"
    - "\x02Elapsed time:\x02 %{elapsed_time} | \x02Total duration:\x02 %{duration}"
    - "\x02Build details:\x02 %{build_url}"
